name: Deploy AWS Lambda with Pulumi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Pulumi
        run: curl -fsSL https://get.pulumi.com | sh

      - name: Install dependencies
        run: |
          pip install -r iac-l1/requirements.txt
          pip install -r iac-l1/lambda/requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy with Pulumi
        run: |
          export PATH=$HOME/.pulumi/bin:$PATH
          pulumi stack select dev
          pulumi up --yes
